name: Build and Test

permissions: read-all

on:
  push:
    branches:
    - master
    - develop
    - gh-actions-test
  pull_request:
    branches:
    - master
    - develop

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # See https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version:
        - file: 3.8.0
          gh: 3.8.0
        - file: 3.9.0
          gh: 3.9.0
        - file: 3.10.0
          gh: 3.10.0
        - file: 3.11.0
          gh: 3.11.0
        - file: 3.12.0
          gh: 3.12.0

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version.gh }}
    - name: Install nvm
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - name: Set up .python-version
      run: |
        echo "${{ matrix.python-version.file }}"
        echo "${{ matrix.python-version.file }}" > .python-version
        cat .python-version
    - name: Install Bash (Ubuntu)
      run: sudo apt-get update && sudo apt-get install -y bash grep xxd git xxhash
    - name: Run everything
      run: |
        bash scripts/pre.sh
